// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/note.dart';
import 'data/models/todo.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7612143447376977849),
    name: 'Note',
    lastPropertyId: const obx_int.IdUid(7, 2887377043495174407),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4364856825499131396),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2699663634816043516),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 734846893174983316),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7720095722418997048),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4604444566296971116),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3465493464160321256),
        name: 'isPinned',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2887377043495174407),
        name: 'isArchived',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6514403910733962082),
    name: 'Todo',
    lastPropertyId: const obx_int.IdUid(5, 1134652061935522025),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3687604873705685839),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1081367711153185566),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1531708826926806787),
        name: 'isCompleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3931916516389356867),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1134652061935522025),
        name: 'noteId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 6514403910733962082),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Note: obx_int.EntityDefinition<Note>(
      model: _entities[0],
      toOneRelations: (Note object) => [],
      toManyRelations: (Note object) => {},
      getId: (Note object) => object.id,
      setId: (Note object, int id) {
        object.id = id;
      },
      objectToFB: (Note object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final contentOffset = fbb.writeString(object.content);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, contentOffset);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(5, object.isPinned);
        fbb.addBool(6, object.isArchived);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final isPinnedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final isArchivedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final object = Note(
          id: idParam,
          title: titleParam,
          content: contentParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          isPinned: isPinnedParam,
          isArchived: isArchivedParam,
        );

        return object;
      },
    ),
    Todo: obx_int.EntityDefinition<Todo>(
      model: _entities[1],
      toOneRelations: (Todo object) => [],
      toManyRelations: (Todo object) => {},
      getId: (Todo object) => object.id,
      setId: (Todo object, int id) {
        object.id = id;
      },
      objectToFB: (Todo object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addBool(2, object.isCompleted);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.noteId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final isCompletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final noteIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final object = Todo(
          id: idParam,
          title: titleParam,
          isCompleted: isCompletedParam,
          createdAt: createdAtParam,
          noteId: noteIdParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Note] entity fields to define ObjectBox queries.
class Note_ {
  /// See [Note.id].
  static final id = obx.QueryIntegerProperty<Note>(_entities[0].properties[0]);

  /// See [Note.title].
  static final title = obx.QueryStringProperty<Note>(
    _entities[0].properties[1],
  );

  /// See [Note.content].
  static final content = obx.QueryStringProperty<Note>(
    _entities[0].properties[2],
  );

  /// See [Note.createdAt].
  static final createdAt = obx.QueryDateProperty<Note>(
    _entities[0].properties[3],
  );

  /// See [Note.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Note>(
    _entities[0].properties[4],
  );

  /// See [Note.isPinned].
  static final isPinned = obx.QueryBooleanProperty<Note>(
    _entities[0].properties[5],
  );

  /// See [Note.isArchived].
  static final isArchived = obx.QueryBooleanProperty<Note>(
    _entities[0].properties[6],
  );
}

/// [Todo] entity fields to define ObjectBox queries.
class Todo_ {
  /// See [Todo.id].
  static final id = obx.QueryIntegerProperty<Todo>(_entities[1].properties[0]);

  /// See [Todo.title].
  static final title = obx.QueryStringProperty<Todo>(
    _entities[1].properties[1],
  );

  /// See [Todo.isCompleted].
  static final isCompleted = obx.QueryBooleanProperty<Todo>(
    _entities[1].properties[2],
  );

  /// See [Todo.createdAt].
  static final createdAt = obx.QueryDateProperty<Todo>(
    _entities[1].properties[3],
  );

  /// See [Todo.noteId].
  static final noteId = obx.QueryIntegerProperty<Todo>(
    _entities[1].properties[4],
  );
}
